name: Laravel

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DB_DATABASE: laravel_testing
      DB_USER: root
      DB_PASSWORD: root
    steps:
    - name: Set up MySQL
      run: |
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
#     - uses: actions/checkout@v2
#     - name: Deploy to Production
#       uses: appleboy/ssh-action@master
#       with:
#         host: ge-dev-01.designa.studio
#         username: www-data
#         key: ${{ secrets.SSH_DESIGNA_DEV_PRIVATE_KEY }}
#         port: 22
#         use_insecure_cipher: true
#         script: |
#           cd designa.studio/dev/designa-app
        
